### ISSUE TITLE
The performance on DukeMTMC-reID set is extremely lower than you report.

### ISSUE THREAD

**Issue by yoon28** [GNAYUOHZ/ReID-MGN#10]
The performance on DukeMTMC-reID set is extremely lower than you report. 
---------
[With    Re-Ranking] mAP: 0.3625 rank1: 0.4654 rank3: 0.5274 rank5: 0.5597 rank10: 0.6154
[Without Re-Ranking] mAP: 0.2323 rank1: 0.3968 rank3: 0.5004 rank5: 0.5498 rank10: 0.6185
------
Above is the results on Dukeset. I tested it with weights you shared.
However, the performance on MARKET1501 is reproducible with the pre-trained weights.
So I suspect that this is caused by the absence of appropriate weights.
Anyway, could you share the weight file that is trained for DukeMTMC-reID?

**Comment by GNAYUOHZ** [comment]
hi, did you change the num_classes in network.py ? correspond to the num_class in Duke dataset

**Comment by GNAYUOHZ** [comment]
hi, have you tried to train in Dukeset, And then test it ?  ps. change num_class in network.py for different dataset.
