### ISSUE TITLE
A quetions about the initial distances for re-ranking.

### ISSUE THREAD

**Issue by huge123** [GNAYUOHZ/ReID-MGN#12]
```
 q_g_dist = np.dot(qf, np.transpose(gf)) 
 q_q_dist = np.dot(qf, np.transpose(qf))  
 g_g_dist = np.dot(gf, np.transpose(gf)) 
 dist = re_ranking(q_g_dist, q_q_dist, g_g_dist)
```

Thanks for sharing the codes, but I have a quetion when I read it. why the initial distance matrices for re-ranking are the correlation matrices of features, not  the Mahalanobis distance ?

**Comment by GNAYUOHZ** [comment]
I think it may be ok using different distance

**Comment by huge123** [comment]
Thanks, I think I have got the answer
