### ISSUE TITLE
why do you add the same features twice in extract_feature.py

### ISSUE THREAD

**Issue by LibreAgent2025** [GNAYUOHZ/ReID-MGN#19]
I found you extract the features from the same images twice, then you add those features, why do you do that?just because of the trick of computing the norm, or other thing?

**Comment by GNAYUOHZ** [comment]
The image is just flipped, this can improve a little bit of accuracy(0.5 % maybe)

**Comment by Margrate** [comment]
mAP = 86.15%, is it the result of Multiple Query?
