### ISSUE TITLE
The behavior of average_precision_score is different in some scikit-learn versions

### ISSUE THREAD

**Issue by ghost** [GNAYUOHZ/ReID-MGN#2]
Hey, thanks for sharing your code!
I wonder which version of scikit-learn are you using. I found that with version > 0.18，the mAP calculated by average_precision_score can be different from common evalution code of market 1501

**Comment by GNAYUOHZ** [comment]
Hi.
Sorry to reply late.I've been busy with exams recently.
The version of sklearn is 0.19.1. I haven't studied the evaluation code in depth yet.I will study it later.
You can refer to the [open-reid ](https://github.com/Cysu/open-reid) code.
Thank you.
