### ISSUE TITLE
Results from default settings

### ISSUE THREAD

**Issue by bityangke** [GNAYUOHZ/ReID-MGN#3]
I have trained and evaluated using your default setting, results below can be taken as a reference by others.
```
start evaluate
[With    Re-Ranking] mAP: 0.9293 rank1: 0.9483 rank3: 0.9676 rank5: 0.9736 rank10: 0.9795
[Without Re-Ranking] mAP: 0.8544 rank1: 0.9376 rank3: 0.9700 rank5: 0.9783 rank10: 0.9863

```

**Comment by bityangke** [comment]
Thanks for sharing first.
I found the results were about 1 percent lower than the reported results by you.
Did you achieve the best results with your default setting?

**Comment by GNAYUOHZ** [comment]
Hi.
Sorry to reply late.I've been busy with exams recently.
The only 2 differences are learning rate 1e-4 or 2e-4, and batchid 16 or 8 or 4.
When batchid is 16, I found the result will be lower.
You can try batchid=4.
Thank you.

**Comment by bityangke** [comment]
Sorry for late response.
Got it. Thanks very much!
Closed！
