### ISSUE TITLE
Can you provide test mode code

### ISSUE THREAD

**Issue by TanLingxiao** [GNAYUOHZ/ReID-MGN#4]
How to test a single image of my own or in the dataset.

**Comment by GNAYUOHZ** [comment]
Hi.
Do you mean extract the feature of a single image ？

**Comment by TanLingxiao** [comment]
> Hi.
> Do you mean extract the feature of a single image ？

Could you provide a demo to show how to search a designated images from datasets?

**Comment by GNAYUOHZ** [comment]
Yes. I've been busy with exams recently. Maybe next week.

**Comment by TanLingxiao** [comment]
> Yes. I've been busy with exams recently. Maybe next week.

Thank you very much!

**Comment by GNAYUOHZ** [comment]
Hi,
I updated it.
Now it can visualize rank10 query result of one image (query from bounding_box_test).
See Visualize in README.md.

**Comment by TanLingxiao** [comment]
> Hi,
> I updated it.
> Now it can visualize rank10 query result of one image (query from bounding_box_test).
> See Visualize in README.md.

Thank you ,I will try it.
