### ISSUE TITLE
Is the model structure different from the original paper?

### ISSUE THREAD

**Issue by ys198918** [GNAYUOHZ/ReID-MGN#5]
In the paper, global features from each part for softmax loss are 2048d. In your code , you did reductions to 256d. In network.py, the bottle neck for classification is always 256, although same layers named with '2048'. Is that a mistake or did you do that for a reason?

**Comment by GNAYUOHZ** [comment]
Hi. 
I think it is a mistake. Have you tried the 2048d? Can you tell me the result? Thank you very much!

**Comment by haoranD** [comment]
> In the paper, global features from each part for softmax loss are 2048d. In your code , you did reductions to 256d. In network.py, the bottle neck for classification is always 256, although same layers named with '2048'. Is that a mistake or did you do that for a reason?

Also, Have you tried the 2048d? Can you please share the results? Thank you!

**Comment by wzjiang** [comment]
I tried the 2048d.  marke→Rank1:93.38  MAP:83.73. duke→rank1：86.58；map：74.24.

**Comment by ys198918** [comment]
I don't remenber the exact result of 2048d, I just remenber it's a lit lower than the result in the paper.
