### ISSUE TITLE
Did you test on CUHK03_NP ?

### ISSUE THREAD

**Issue by ys198918** [GNAYUOHZ/ReID-MGN#6]
The result seems to be much higher than the paper

**Comment by wangminjie920705** [comment]
> The result seems to be much higher than the paper
Dear student,I want to have a try on CUHK03，but I don't know how to do it.Can you tell me,thanks you very much!

**Comment by ys198918** [comment]
> > The result seems to be much higher than the paper
> > Dear student,I want to have a try on CUHK03，but I don't know how to do it.Can you tell me,thanks you very much!

create a new class, just like market1501 in data.py

**Comment by wangminjie920705** [comment]
> > > The result seems to be much higher than the paper
> > > Dear student,I want to have a try on CUHK03，but I don't know how to do it.Can you tell me,thanks you very much!
> 
> create a new class, just like market1501 in data.py

sorry,I try to do it  but failed.Can I get your data.py.Thanks you very much!
my email:wangminjie920705@163.com

**Comment by GNAYUOHZ** [comment]
Yes when I test on CUHK03, the result is much higher. Maybe it is the difference of metrics.

**Comment by GNAYUOHZ** [comment]
Hi, have you succeeded? If not, I will provide the code.

**Comment by GNAYUOHZ** [comment]
@wangminjie920705 Hi, have you succeeded? If not, I will provide the code.

**Comment by haoranD** [comment]
> @wangminjie920705 Hi, have you succeeded? If not, I will provide the code.

Hi, thank you for your works, it is very excellent. I am sorry that:
1. Can you please share the code for the CUHK03, thank you very much. haoranduan28@gmail.com
2. Can you please give a brief explanation the reason that you got better results?

Thank you and very much.
Sincerely.

**Comment by haoranD** [comment]
Hi, thank you for your works, it is very excellent. I am sorry that:

1. Can you please share the code for the CUHK03, thank you very much. haoranduan28@gmail.com
2. Can you please give a brief explanation the reason that you got better results?

Thank you and very much.
Sincerely.

**Comment by wangminjie920705** [comment]
> @wangminjie920705 Hi, have you succeeded? If not, I will provide the code.

Thanks you! I have successed using CUHK03_NP.

**Comment by GNAYUOHZ** [comment]
@haoranD  HI,thank you.
1. the code to transform CUHK03 has updated. See README for detail.
2. I dont know in fact...

**Comment by haoranD** [comment]
> @haoranD HI,thank you.
> 
> 1. the code to transform CUHK03 has updated. See README for detail.
> 2. I dont know in fact...

Thanks!
