### ISSUE TITLE
The results

### ISSUE THREAD

**Issue by haoranD** [GNAYUOHZ/ReID-MGN#7]
Hi, thanks for your excellent work.

I directly use your code on Market Dataset without any additional changes.

I got only rank1 93.46% mAp 90.68% under 500 epoch, but you got 3% higher.

Can you please give some suggestion about how can I do?

Thank you very much sincerely.

**Comment by GNAYUOHZ** [comment]
After I change 256d to 2048d, I haven't tested it. Maybe somewhere need change too. I will try recently.

**Comment by zhangming8** [comment]
Yeah, thanks for your work. 
my result are( with default setting ):
[With    Re-Ranking] mAP: 0.9195 rank1: 0.9406 rank3: 0.9632 rank5: 0.9691 rank10: 0.9765
[Without Re-Ranking] mAP: 0.8225 rank1: 0.9255 rank3: 0.9626 rank5: 0.9757 rank10: 0.9852

**Comment by haoranD** [comment]
Thanks a lot.

**Comment by haoranD** [comment]
Hi, how's it going? I check the code, but also can not find anything about the issue of the 256d and 2048d....
