### ISSUE TITLE
The result is so terrible

### ISSUE THREAD

**Issue by L-CODERS** [GNAYUOHZ/ReID-MGN#9]
Hi! Thinks for your contribution.I find that I have a very terrible result,map is 0.0048 after 350 epochs,could you give me some advice?

**Comment by GNAYUOHZ** [comment]
hi，have you find the problem？

**Comment by L-CODERS** [comment]
> hi，have you find the problem？

It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.

**Comment by GNAYUOHZ** [comment]
> > hi，have you find the problem？
> 
> It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.

So you mean you can run normally. I also met the problem of low accuracy in 2048d. I don't know how to modify it.

**Comment by L-CODERS** [comment]
> > > hi，have you find the problem？
> > 
> > 
> > It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.
> 
> So you mean you can run normally. I also met the problem of low accuracy in 2048d. I don't know how to modify it.



> > > hi，have you find the problem？
> > 
> > 
> > It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.
> 
> So you mean you can run normally. I also met the problem of low accuracy in 2048d. I don't know how to modify it.

I have sent a email to the author of the paper for the code,but I don't get any responds,do you try to contact the author?

**Comment by GNAYUOHZ** [comment]
> > > > hi，have you find the problem？
> > > 
> > > 
> > > It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.
> > 
> > 
> > So you mean you can run normally. I also met the problem of low accuracy in 2048d. I don't know how to modify it.
> 
> > > > hi，have you find the problem？
> > > 
> > > 
> > > It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.
> > 
> > 
> > So you mean you can run normally. I also met the problem of low accuracy in 2048d. I don't know how to modify it.
> 
> I have sent a email to the author of the paper for the code,but I don't get any responds,do you try to contact the author?

Me too. So have the author responded to you ?

**Comment by L-CODERS** [comment]
> > > > > hi，have you find the problem？
> > > > 
> > > > 
> > > > It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.
> > > 
> > > 
> > > So you mean you can run normally. I also met the problem of low accuracy in 2048d. I don't know how to modify it.
> > 
> > 
> > > > > hi，have you find the problem？
> > > > 
> > > > 
> > > > It's confused,I run the code without any changes first time,the map is 0.006 after 350 epochs,then I changed the 256d to 2048d,the map is 77 after 500 epochs.Now,I change the 2048d back to 256d,the model is still running,but the map is 83 after 100 epochs.
> > > 
> > > 
> > > So you mean you can run normally. I also met the problem of low accuracy in 2048d. I don't know how to modify it.
> > 
> > 
> > I have sent a email to the author of the paper for the code,but I don't get any responds,do you try to contact the author?
> 
> Me too. So have the author responded to you ?

No,I have contacted the second author,but no responding.
